# MobiAct Feature Extraction Config

pipeline:
  sampling_rate_hz: 87.0
  n_bins_energy: 5

stage1:
  n_bins: 5
  max_samples: null

stage2a:
  n_bins: 5

stage2b:
  n_bins: 5
  max_samples: 1000
  n_classes: 11  # can be 9 or 11
